
services:
  db:
    image: postgres:latest
    container_name: gestorProBeebit-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestorpro
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: gestorProBeebit-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: gestorpro
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    command: npm run start

  frontend:
    build: ./frontend
    container_name: gestorProBeebit-frontend
    restart: always
    depends_on:
      - api
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
