# Usa la imagen de Node.js
FROM node:18-alpine

# Crea y usa el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar la API
CMD ["npm", "run", "start:dev"]
